
export const GET_SYSTEM_LIST = "GET_SYSTEM_LIST"

export const GET_PERMISSIONMENU_LIST = "GET_PERMISSIONMENU_LIST"

export const GET_MENU_TREE = "GET_MENU_TREE"

export const SET_OPERATE_BTNS = "SET_OPERATE_BTNS"

export const SET_INCLUDES = "SET_INCLUDES"

